### ISSUE TITLE
remove winrm from targeting in README

### ISSUE THREAD

**Issue by ejaronne** [mitre/aws-rds-crunchy-data-postgresql-9-stig-baseline#1]
(typo) remove "-t winrm://<hostip> --user '<admin-account>' --password=<password> "

**Comment by asturtevant** [comment]
updated the readme to change winrm to ssh instead

**Comment by ejaronne** [comment]
shouldn't this have no targeting, since it is on AWS RDS? The IP and port of the database are in the attributes

**Comment by asturtevant** [comment]
Ah, yes that correct, I'll go ahead and update that
